version: '3.8'

services:
  nginx:
    container_name: nginx-container
    build: requirements/nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
    restart: always
    volumes:
      - wordpress-dbase:/var/www/html/wordpress
    networks:
      - my_network
  wordpress:
    container_name: wordpress-container
    build: requirements/wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress-dbase:/var/www/html/wordpress
    networks:
      - my_network
  mariadb:
    container_name: mariadb-container
    build: requirements/mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb-dbase:/var/lib/mariadb
    networks:
      - my_network
  redis:
    container_name: redis
    build: requirements/bonus/redis
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .env
    networks:
      - my_network
  website:
    container_name: website
    build: requirements/bonus/website
    restart: always
    ports:
      - 4000:4000
    networks:
      - my_network
  adminer:
    container_name: adminer
    build: requirements/bonus/adminer
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wordpress-dbase:/var/www/html/wordpress
    ports:
      - 7000:7000
    networks:
      - my_network
  cadvisor:
    container_name: cadvisor
    build: requirements/bonus/cadvisor
    restart: always
    ports:
      - 8080:8080
    networks:
      - my_network
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
networks:
  my_network:
    driver: bridge

volumes:
  wordpress-dbase:
    name: wordpress-dbase
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/abenlahb/data/wordpress-dbase
  mariadb-dbase:
    name: mariadb-dbase
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/abenlahb/data/mariadb-dbase
